services:
  # FRONTEND
  app:
    build:
      context: ./example-frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports:
      - 3000:5000
    container_name: example-frontend-prod # This will name the container example-front-prod
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    command: ["serve", "-s", "-l", "5000", "build"]

  # BACKEND
  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: example-backend-prod # This will name the container example-backend-prod
    environment:
      REQUEST_ORIGIN: http://localhost:3000
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    command: ["./server"]
    depends_on:
      - db

  # REDIS 
  redis:
    image: redis:alpine
    container_name: redis-prod
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]

  # POSTGRES DATABASE
  db:
    image: postgres:16.6-alpine3.21
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres-db-prod